apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: welcome-example
  template:
    metadata:
      labels:
        app: welcome-example
    spec:
      containers:
      - name: welcome-example
        image: nginx
        ports:
        - containerPort: 80
