apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app
spec:
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      containers:
      - name: welcome-app
        image: welcome-app
        ports:
        - containerPort: 3000
