apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome
spec:
  replicas: 3
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
      - name: welcome
        image: welcome
        ports:
        - containerPort: 80
