name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t welcome-app .
      - run: docker push welcome-app
  deploy:
    runs-on: kubernetes-agents
    steps:
      - uses: actions/checkout@v2
      - run: kubectl apply -f deployment.yaml
