name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t welcome-app .
      - name: Push the Docker image to ECR
        run: aws ecr create-repository --repository-name welcome-app
        run: docker push welcome-app
      - name: Deploy the application to Kubernetes
        run: kubectl apply -f deployment.yaml
