
        name: CI

        on: [push]

        jobs:
          build:
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v2
            - name: Build Docker image
              run: docker build -t welcome-example .
            - name: Push Docker image to Docker Hub
              run: docker push welcome-example
            - name: Deploy to Kubernetes
              uses: GoogleCloudPlatform/github-actions/deploy-to-kubernetes@v0
              with:
                args: --namespace=default --image=welcome-example:latest
          test:
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v2
            - name: Run tests
              run: npm test
        